# This workflow is largely inspired by the following workflows:
# https://github.com/arichornlover/uYouEnhanced/blob/main/.github/workflows/buildapp.yml
# https://github.com/ISnackable/YTCubePlus/blob/main/.github/workflows/Build.yml
# https://github.com/BandarHL/BHTwitter/actions/workflows/build.yml

name: Build and Package Turkish SCInsta

on:
  workflow_dispatch:
    inputs:
      decrypted_instagram_url:
        description: "Direct URL for the decrypted Instagram IPA (Read the FAQ if you don't know how to get it)"
        default: ""
        required: true
        type: string
      upload_artifact:
        description: "Upload the build result (artifact)"
        default: true
        required: false
        type: boolean
          
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build SCInsta
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout the Main Repository
        uses: actions/checkout@v4
        with:
          path: main
          submodules: recursive

      - name: Install Dependencies
        run: brew install ldid dpkg make

      - name: Set PATH Environment Variable
        run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH

      - name: Setup Theos
        uses: actions/checkout@v4
        with:
          repository: theos/theos
          ref: master
          path: ${{ github.workspace }}/theos
          submodules: recursive
            
      - name: Cache SDKs
        id: SDK
        uses: actions/cache@v4
        env:
          cache-name: iPhoneOS14.5.sdk
        with:
          path: ${{ github.workspace }}/theos/sdks/
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}

      - name: Download iOS SDK
        if: steps.SDK.outputs.cache-hit != 'true'
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/xybp888/iOS-SDKs/
          cd iOS-SDKs
          git sparse-checkout set --no-cone iPhoneOS14.5.sdk
          git checkout
          mv *.sdk $THEOS/sdks
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Prepare Instagram IPA
        run: |
          cd main
          mkdir -p packages
          wget "$Instagram_URL" --no-verbose -O packages/com.burbn.instagram.ipa
          ls -la packages
            
        env:
          THEOS: ${{ github.workspace }}/theos
          Instagram_URL: ${{ inputs.decrypted_instagram_url }}

      - name: Get SCInsta Version
        id: scinsta_version
        run: |
          SCINSTA_VERSION=$(awk '/Version:/ {print $2}' main/control)
          echo "SCINSTA_VERSION=${SCINSTA_VERSION}" >> "$GITHUB_ENV"
          echo "version=${SCINSTA_VERSION}" >> "$GITHUB_OUTPUT"
            
      - name: Build SCInsta tweak for sideload (as IPA)
        run: |
          pip install --force-reinstall https://github.com/asdfzxcvbn/pyzule-rw/archive/main.zip
            
          cd main
          ls -la

          ./build.sh sideload
          ls -la packages
            
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Rename IPA with Version Info
        run: |
          cd main/packages
          mv "$(ls -t | head -n1)" "SCInsta_sideloaded_v${SCINSTA_VERSION}.ipa"

      - name: Pass Package Name to Upload Action
        id: package_name
        run: |
          echo "package=$(ls -t main/packages | head -n1)" >> "$GITHUB_OUTPUT"

      - name: Upload Artifact
        if: ${{ inputs.upload_artifact }}
        uses: actions/upload-artifact@v4
        with:
          name: SCInsta_sideloaded_v${{ steps.scinsta_version.outputs.version }}
          path: ${{ github.workspace }}/main/packages/${{ steps.package_name.outputs.package }}
          if-no-files-found: error
